language: python
python:
  - "3.6"
cache: pip
install:
  - pip install tox-travis coveralls
script:
  - tox
deploy:
  provider: pypi
  skip_cleanup: true
  distributions: "bdist_wheel"
  user: "__token__"
  password:
    secure: "JLacHTufuPyST9CQhfXe+I0zLdUnQHUjQ1CbaDYfFUpci1IQAQmDdkEuj00gTBom4HvHvamBmTFLS1dAWUWFAnHguymZcRnhIuLyXJUXmXGo4+js5V3Mu/1Lddl9kGqNZWvZe8Mq69hZzJIG6T9yJAmDIQA7dmHCdnefjC/IyRZXQiAC6GwWMDnc9EeSxsr7GCgZ/GCKtuO7RKnGWPzI/J8JBsAKfmddAGmUWuTfWcA/c+c9RMOwmGoggReqNjC3tMG+m2zDoVxCOmc26p/NJZYc0fYhdV2QWLU9A6C7cg/gt9wrePurtdqnMJ4p0qCLEjONOjTqla0sZLlKdgG22/F3J+hXCuKCRAGT2x4kBY1dWBh5UkN8+3gW067Td+xTkX/CvJAgVbfDIZ83BRemI/zhLxLZLCw8rHTPMnrFfzFg+137twnsa9wqAosYCd7ScAWTR/aeObRral5V+Eqq7crA0lpFqkNRmI5n/HNKz1Z+N6mfs7ngkJJLA84E6L/jbwozS4svD7+GJ2rm/ocdh55V4fms4qIvLwk+H/B52YNb2Ts0UPw8XCHxcpBnDp6gztUQa0MzlVrm5Cm0S6KwLnvxJTOXgiLDILo6ukoGsJvGvkXpJhqoTtQGM16wvnJPSWSUwSSkLxd9eNSsAN5YUMaJgW8Qp7kqWfC89igFm9c="
  on:
    branch: master
  skip_existing: true
after_success:
- coveralls --verbose